[tool.black]
line-length = 100
target-version = ["py311"]

[tool.ruff]
line-length = 100
select = ["E","F","I"]  # keep it simple: errors, flake8, import sort
ignore = ["E501"]       # ignore long lines

[tool.isort]
profile = "black"